In [6]:
import numpy as np

In [16]:
# 1
tableau = np.arange(10)
print(tableau)

[0 1 2 3 4 5 6 7 8 9]


In [17]:
# 2
matrice = tableau.reshape(2, 5)
print(matrice)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [18]:
# 3
reversed_matrice = np.fliplr(matrice)
print(reversed_matrice)

[[4 3 2 1 0]
 [9 8 7 6 5]]


In [23]:
# 4
somme_colonne = matrice.sum(axis=0)
print(somme_colonne)

[ 5  7  9 11 13]


In [22]:
# 5
impairs = tableau[tableau % 2 == 1]
print(impairs)

[1 3 5 7 9]
