In [1]:
import numpy as np

In [4]:
# 1
tableau = np.random.randint(1, 21, (3, 3))
print(tableau)

[[16 15 17]
 [15 14 20]
 [ 3  6 20]]


In [5]:
# 2
min_value = tableau.min()
max_value = tableau.max()
print(min_value,max_value)

3 20


In [6]:
# 3
normalized_array = (tableau - min_value) / (max_value - min_value)
print(normalized_array)

[[0.76470588 0.70588235 0.82352941]
 [0.70588235 0.64705882 1.        ]
 [0.         0.17647059 1.        ]]


In [8]:
# 4
mean_value = tableau.mean()
variance_value = tableau.var()
std_dev_value = tableau.std()

print(mean_value,variance_value,std_dev_value)

14.0 30.22222222222222 5.497474167490214


In [11]:
# 5
tableau_carre = np.where(tableau % 2 != 0, tableau**2, tableau)
print(tableau_carre)

[[ 16 225 289]
 [225  14  20]
 [  9   6  20]]


In [14]:
# 6
mask = tableau > 10
print(mask)

[[ True  True  True]
 [ True  True  True]
 [False False  True]]
